wifi_ssid: "example-ssid"
wifi_password: "example-password"
wifi_ap_ssid: "example-fallback-ap"
wifi_ap_password: "example-fallback-password"
api_key: "example-base64-api-key"
ota_password: "example-ota-password"
